name: Cross Platform CMake build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
